spring.application.name=ChatApplicationBackend


spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username=postgres
spring.datasource.password=Fartline*10b

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
